### ISSUE TITLE
Incorrect NavBar behaviour 

### ISSUE THREAD

**Issue by rabzu** [bryankeller/BLKFlexibleHeightBar#10]
I noticed that when tableview has less than three cells FacebookStyleBar misbehaves. I got this behaviour in my code as well as the provided demo code in this repository. However it works fine when there are lot of cells

Am i missing something?

**Comment by bryankeller** [comment]
You're not missing something - it's definitely a bug in the behavior definer. I'll have a look and get this fixed!

**Comment by rabzu** [comment]
thanks

**Comment by bryankeller** [comment]
https://github.com/bryankeller/BLKFlexibleHeightBar/commit/f95f746c96ffac618fa0ed4bfdf6524ef3b3b484 fixes this. Thanks again for pointing this out to me!

**Comment by rabzu** [comment]
thanks, it works nicely
