### ISSUE TITLE
BLKDelegateSplitter does not work for scrollView delegate calls

### ISSUE THREAD

**Issue by kylebshr** [bryankeller/BLKFlexibleHeightBar#13]
I'm attempting to implement `scrollViewDidScroll` for my UITableView, but the splitter doesn't work with it for some reason. If I set my delegate like this, `scrollViewDidScroll` is called: `tableView.delegate = self`. But if I set it to the splitter, the scrollview method isn't called, even though the TableView Delegate methods are called: 
    
    delegateSplitter = BLKDelegateSplitter(firstDelegate: flexBar.behaviorDefiner, secondDelegate: self)
    activityTable.delegate = delegateSplitter

Really not sure how to fix this, any pointers would be helpful.

**Comment by kylebshr** [comment]
It seems like this works if you make the firstDelegate: self — I still feel this is buggy behavior

**Comment by bryankeller** [comment]
This is fixed now. Thanks for bringing my attention to this issue.
