### ISSUE TITLE
Delegate splitter does not work

### ISSUE THREAD

**Issue by rabzu** [bryankeller/BLKFlexibleHeightBar#15]
I don't think delegate splitter works. You have the following code in your SquareCashStyleViewController demo:

self.delegateSplitter = [[BLKDelegateSplitter alloc] initWithFirstDelegate:behaviorDefiner     secondDelegate: self];
self.tableView.delegate = (id<UITableViewDelegate>)self.delegateSplitter;

tableview delage functions does not work such as:
- (void)scrollViewDidScroll:(UIScrollView *)scrollView 

However, when I use self as the first delegate and the behaviorDefiner as the second delegate then tableview delegate works but then nav bar stops working

self.delegateSplitter = [[BLKDelegateSplitter alloc] initWithFirstDelegate:behaviorDefiner     secondDelegate: self];

is this a bug or am I missing something

P.S. the same in swift

**Comment by bryankeller** [comment]
I'm seeing the same issue. Looking into it now. Thanks for pointing this out.
