### ISSUE TITLE
Changing height of the bar

### ISSUE THREAD

**Issue by sibinbk** [bryankeller/BLKFlexibleHeightBar#2]
Hi Bryan,
First of all great work. This library is awesome. 

Is there any option to change the height of the bar by swiping over the bar (or any other action on the bar itself) rather than scrolling the tableview? Since my project requires the bar to cover the whole view initially, scrolling tableview is not an option for me. 

Thanks.

**Comment by bryankeller** [comment]
Thanks for the kind words!
BLKFlexibleHeightBar has a readwrite property `progress`. You're free to set this from wherever you have access to the bar. Additionally, BLKFlexibleHeightBarBehaviorDefiner, and all subclasses, have methods to "snap" to a progress. You can setup a gesture recognizer to call this method, or directly adjust the `progress` property when appropriate.

**Comment by sibinbk** [comment]
Thanks for the quick reply. 
I did try to change the value of 'progress' already but it does not change anything. Here is the code I tried.  

In viewDidLoad I added two gesture recognizers for Up/Down swipe.
- (void)viewDidLoad
{
    UISwipeGestureRecognizer *swipeUp = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(upSwip:)];
    [swipeUp setDirection:UISwipeGestureRecognizerDirectionUp];
    [self.myCustomBar addGestureRecognizer:swipeUp];
    
    UISwipeGestureRecognizer *swipeDown = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(downSwipe:)];
    [swipeDown setDirection:UISwipeGestureRecognizerDirectionDown];
    [self.myCustomBar addGestureRecognizer:swipeDown];
}

- (void)upSwip:(UISwipeGestureRecognizer *)gesture
{
    NSLog(@"Swiped up");
    self.myCustomBar.progress = 1.0;
}

- (void)downSwipe:(UIGestureRecognizer *)gesture
{
    NSLog(@"Swiped down");
    self.myCustomBar.progress = 0.0;
}

**Comment by bryankeller** [comment]
self.myCustomBar.progress = 0.0;
[self.myCustomBar layoutIfNeeded];
after setting the progress should do the trick!

**Comment by sibinbk** [comment]
Hi Bryan,
Changing 'progress' value is still not working for me.  
But I tried to modify the 'snap' value and works like a charm. 

   - (void)upSwip:(UISwipeGestureRecognizer *)gesture
   {
      [UIView animateWithDuration:0.5 animations:^{
          [self.myCustomBar.behaviorDefiner snapToProgress:1.0 scrollView:self.tableView];
      }];
      NSLog(@"Swiped up");
  }

Once again thank you so much for your help.
Sibin

**Comment by bryankeller** [comment]
My apologies, you can set the progress directly but you must follow it with 
[self.flexibleHeightBar setNeedsLayout];
Sorry about that!
