### ISSUE TITLE
Scroll resistance between tableview and FlexibleHeightBar

### ISSUE THREAD

**Issue by sibinbk** [bryankeller/BLKFlexibleHeightBar#3]
Hi Bryan,

Is it possible to add a scroll resistance (rubber band effect) between the FelexibleHeightBar and the tableview? What I mean is the Bar should stays at the minimum height until the tableview is pulled down and top of the tableview reaches some distance from the bottom of the bar. Most of the pull to refresh libraries adds this type of effect. 
I believe this feature is not the scope of this project but if you could include it or provide some guidance on implementing, it would be really helpful.

Thanks

**Comment by bryankeller** [comment]
That's a cool idea! You can definitely make something like that with a custom behavior definer. I had a little time so I put together a solution. The behavior is pretty similar to `SquareCashStyleBehaviorDefiner`, so I just subclassed that. My comments in the code should explain it.

`RubberBandStyleBehaviorDefiner.h`
```objc
#import "SquareCashStyleBehaviorDefiner.h"

@interface RubberBandStyleBehaviorDefiner : SquareCashStyleBehaviorDefiner

@end
```

and

`RubberBandStyleBehaviorDefiner.m`
```objc
#import "RubberBandStyleBehaviorDefiner.h"

#import "BLKFlexibleHeightBar.h"

@implementation RubberBandStyleBehaviorDefiner

- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    // Behave like square cash whenever we're not already minimum height
    if(self.flexibleHeightBar.progress != 1.0)
    {
        [super scrollViewDidScroll:scrollView];
    }
}

- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate
{
    // Stretch scroll view by 100 pixels to snap it to maximum height
    if(scrollView.contentOffset.y < -scrollView.contentInset.top - 100.0)
    {
        [UIView animateWithDuration:0.2 animations:^{
            
            [self snapToProgress:0.0 scrollView:nil];
            
        }];
    }
    else
    {
        [super scrollViewDidEndDragging:scrollView willDecelerate:decelerate];
    }
}

@end
```

<img src="http://foxweb.marist.edu/users/stbk/RubberBandStyle.gif" alt="RubberBandStyleBehaviorDefiner" width="600"/>

**Comment by sibinbk** [comment]
That's awesome. It works but still require some tweaks. I will try to sort it out and let you know soon.

Thanks.
