### ISSUE TITLE
UITableView not rendered correctly 

### ISSUE THREAD

**Issue by dorinsimina** [bryankeller/BLKFlexibleHeightBar#36]
Hi all,

I have an issue when adding the navigation bar with an UITableView. When the screen is loaded the table is not correctly rendered below the navigation bar. Once I start scrolling, the navigation bar jumps on top and from that moment the table looks fine.

Can someone has a clue what might be the problem?

![img_0231](https://cloud.githubusercontent.com/assets/5087043/8000854/4f6a3e94-0b68-11e5-90c4-f18335329a5e.PNG)
![img_0232](https://cloud.githubusercontent.com/assets/5087043/8000855/4f9c5fa0-0b68-11e5-9212-f01ae7242eff.PNG)

Thanks.

**Comment by bryankeller** [comment]
You have to manually set the `contentInset` of your scroll view after you set up the `BLKFlexibleHeightBar`. Check out `-viewDidLoad:` in the demo project's view controllers for more info. Also the README.md covers this. Let me know if that works for you!

**Comment by dorinsimina** [comment]
I've already set:

<code>
self.tableView.contentInset = UIEdgeInsetsMake(self.myCustomBar.maximumBarHeight, 0.0, 0.0, 0.0);
</code>

And prior I have:

<code>
self.myCustomBar = [[NuggetDetailStyleBar alloc] initWithFrame:CGRectMake(0.0, 0.0, CGRectGetWidth(self.view.frame), 300) andText:self.library.name];
</code>
<code>
        SquareCashStyleBehaviorDefiner *behaviorDefiner = [[SquareCashStyleBehaviorDefiner alloc] init];
        [behaviorDefiner addSnappingPositionProgress:0.0 forProgressRangeStart:0.0 end:0.5];
        [behaviorDefiner addSnappingPositionProgress:1.0 forProgressRangeStart:0.5 end:1.0];
        behaviorDefiner.snappingEnabled = YES;
        behaviorDefiner.elasticMaximumHeightAtTop = YES;
        self.myCustomBar.behaviorDefiner = behaviorDefiner;
        [self.view addSubview:self.myCustomBar];
</code>

<code>
self.delegateSplitter = [[BLKDelegateSplitter alloc] initWithFirstDelegate:behaviorDefiner secondDelegate:self];
        self.tableView.delegate = (id<UITableViewDelegate>)self.delegateSplitter;
</code>

**Comment by fatgue** [comment]
Do you found any solution? I have the same problem. 

if tableViewData.count < 4 {
                self.behaviorDefiner.snappingEnabled = true
                UIView.animateWithDuration(0.4, delay: 0, options: UIViewAnimationOptions.TransitionNone, animations: { () -> Void in
                    self.headerView.behaviorDefiner.snapToProgress(0, scrollView: self._imageTableView)
                    
                    }, completion: { (finished) -> Void in
                        self._imageTableView.setNeedsLayout()
                        self._imageTableView.layoutIfNeeded()
                })                
            }

If i have 4 rows left and delete one, the header scrolls down but my tableview is under the header.

**Comment by dorinsimina** [comment]
I've changed the tableview created programatically with an auto layout widget from interface builder and it worked. 

I didn't have the time to check more deeply a solution for my case in which the tableview was added programatically.

**Comment by fatgue** [comment]
ok this worked for me now

UIView.animateWithDuration(0.4, delay: 0, options: UIViewAnimationOptions.TransitionNone, animations: { () -> Void in
                        self.headerView.behaviorDefiner.snapToProgress(0, scrollView: self._imageTableView)
                        self._imageTableView.setContentOffset(CGPointMake(0, -280), animated: false)

                    }, completion: { (finished) -> Void in

                        self._imageTableView.setNeedsLayout()
                        self._imageTableView.layoutIfNeeded()
                    })
