### ISSUE TITLE
problem with deleting tableview rows

### ISSUE THREAD

**Issue by fatgue** [bryankeller/BLKFlexibleHeightBar#7]
Hi,

first thanks for the great work. Your code is exactly what i need. 
But i have a problem by deleting tableview rows.

If i have 3 or 4 bigger cells on my tableview and if i want delete them, the BLKFlexibleHeightBar don't
scroll down automatically to "maximumBarHeight". I have to scroll down manually to see the bar again.
Is there any solution for my problem? the red bar above is the navigation bar not the BLKFlexibleHeightBar. My minimumBarHeight is zero.

![bildschirmfoto 2015-03-19 um 12 26 00](https://cloud.githubusercontent.com/assets/10461896/6729532/8262e8b8-ce33-11e4-8d54-9ba75e5a4cb1.png)

sorry for my english

**Comment by bryankeller** [comment]
You could create a custom behavior that monitors the table view and adjust's the bar's progress based on cells being removed.
